name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.0, 1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Deno v${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: v${{ matrix.deno-version }}
      - name: Run Linter
        run: deno fmt --check
      - name: Run Tests
        run: deno task test
